name: SmartNote
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  algolia: ^1.0.0
  flutter:
    sdk: flutter
  http: ^0.13.6          # Downgrade this version
  provider: ^6.1.0
  flutter_markdown: ^0.6.10
  file_picker: ^6.1.0
  path_provider: ^2.1.0
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
